
name: Deploy to Pages

on:
  push:
    branches: ["*"] # Remember to change back to main for testing

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup Misc
        run: |
            cp -r borders src/
            cp -r badges src/
            cp -r geolocation src/
            cp -r globalSettings src
            mkdir -p src/RoValra/Settings
            cp globalSettings/featurekill.json src/RoValra/Settings/config.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
